name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o simple-windows-x64.exe cmd/simple/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o simple-linux-x64 cmd/simple/main.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o simple-darwin-x64 cmd/simple/main.go
          zip simple-windows-x64.exe.zip simple-windows-x64.exe
          zip simple-linux-x64.zip simple-linux-x64
          zip simple-darwin-x64.zip simple-darwin-x64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release windows
        uses: actions/upload-release-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./simple-windows-x64.exe.zip
          asset_name: simple-windows-x64.exe.zip
          asset_content_type: application/zip
      - name: Upload Release linux
        uses: actions/upload-release-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./simple-linux-x64.zip
          asset_name: simple-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload Release darwin
        uses: actions/upload-release-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./simple-darwin-x64.zip
          asset_name: simple-darwin-x64.zip
          asset_content_type: application/zip  